spring:
  application:
    name: splearn
  flyway:
    enabled: true
    locations: classpath:db/migration
  docker:
    compose:
      lifecycle-management: start_only
  sql:
    init:
      mode: never

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
